//
//  GrayScottRenderer.swift
//  PhysicsBackground
//
//  Metal rendering engine. Conforms to MTKViewDelegate.
//  Owns the full GPU pipeline: ping-pong simulation → coloriseAndLight → render.
//
//  Key SPM difference from app-embedded Metal:
//    `device.makeDefaultLibrary(bundle: .module)` loads the compiled .metallib
//    from the package bundle. Never use `device.makeDefaultLibrary()` here —
//    that only searches the app's main bundle, not the package's.
//
//  Pipeline (per frame):
//    grayScottStep × N   — advances the reaction-diffusion PDE (compute)
//    colorizeAndLight    — maps V → RGB + Blinn-Phong shading (compute)
//    vertexPassthrough   — full-screen quad to drawable (render)
//
//  Lighting changes reach the renderer via updateLighting(_:), called from
//  MetalSimView.updateUIView — no simulation reset needed.
//

import Metal
import MetalKit
import QuartzCore
import simd

// MARK: - GPU uniform structs
// Byte layout must be identical to the structs in GrayScottSimulation.metal.

/// Matches `struct SimUniforms` in the Metal shader.
/// All scalar types — no padding required.
struct SimUniforms {
    var Du:     Float
    var Dv:     Float
    var feed:   Float
    var kill:   Float
    var dt:     Float
    var width:  UInt32
    var height: UInt32
}

/// Matches `struct ColourUniforms` in the Metal shader.
/// Uses SIMD4<Float> to match Metal's float4 (16-byte alignment).
struct ColourUniforms {
    var low:      SIMD4<Float>
    var mid:      SIMD4<Float>
    var high:     SIMD4<Float>
    var midPoint: Float
    var gamma:    Float
}

/// Matches `struct LightingUniforms` in the Metal shader.
///
/// Layout (Swift stride = Metal sizeof = 64 bytes):
///   offset  0 — float4 lightDir     (16 bytes)
///   offset 16 — float4 lightColour  (16 bytes)
///   offset 32 — float  ambient       (4 bytes)
///   offset 36 — float  diffuse        (4 bytes)
///   offset 40 — float  specular       (4 bytes)
///   offset 44 — float  shininess      (4 bytes)
///   offset 48 — float  heightScale    (4 bytes)
///   offset 52 — 12 bytes implicit padding → total 64 bytes ✓
struct LightingUniforms {
    var lightDir:    SIMD4<Float>   // xyz = direction toward light (normalised), w unused
    var lightColour: SIMD4<Float>   // xyz = linear RGB, w unused
    var ambient:     Float
    var diffuse:     Float
    var specular:    Float
    var shininess:   Float
    var heightScale: Float
}

// MARK: - GrayScottRenderer

public final class GrayScottRenderer: NSObject, MTKViewDelegate {

    // Exposed so MetalSimView.makeUIView can pass the same device to MTKView.
    let device: MTLDevice

    private let commandQueue:        MTLCommandQueue
    private let stepPipeline:        MTLComputePipelineState
    private let colorizePipeline:    MTLComputePipelineState   // original flat pass (lighting off)
    private let colorizeLitPipeline: MTLComputePipelineState   // Blinn-Phong pass (lighting on)
    private let renderPipeline:      MTLRenderPipelineState

    private var pingTex:    MTLTexture   // simulation state — read source
    private var pongTex:    MTLTexture   // simulation state — write target
    private var displayTex: MTLTexture   // colorized + lit output — rgba8Unorm

    private var simUniforms:     SimUniforms
    private var colUniforms:     ColourUniforms
    private var lightingUniforms: LightingUniforms

    private let threadgroupSize:  MTLSize
    private let threadgroupCount: MTLSize
    private let stepsPerFrame:    Int
    private let texSize:          Int

    // Lighting is mutable — updated via updateLighting(_:) without restarting simulation.
    private var lighting:  PhysicsLighting
    private let startTime: CFTimeInterval   // for animated light orbit

    // MARK: init

    init?(config: PhysicsConfig, texSize: Int = 512) {
        guard
            let dev   = MTLCreateSystemDefaultDevice(),
            let queue = dev.makeCommandQueue()
        else { return nil }

        self.device       = dev
        self.commandQueue = queue
        self.texSize      = texSize
        self.stepsPerFrame = config.preset.stepsPerFrame
        self.lighting     = config.lighting
        self.startTime    = CACurrentMediaTime()

        // Load the Metal library from the package bundle.
        // Bundle.module is generated by SPM and points to the package's resource bundle.
        guard let lib = try? dev.makeDefaultLibrary(bundle: .module) else {
            assertionFailure("""
                GrayScottRenderer: could not load Metal library from package bundle.
                Ensure Package.swift includes `.process("Shaders")` in the target's resources.
                """)
            return nil
        }

        guard
            let stepFn          = lib.makeFunction(name: "grayScottStep"),
            let colorizeFn      = lib.makeFunction(name: "colorize"),
            let colorizeLitFn   = lib.makeFunction(name: "colorizeAndLight"),
            let vertFn          = lib.makeFunction(name: "vertexPassthrough"),
            let fragFn          = lib.makeFunction(name: "fragmentPassthrough")
        else { return nil }

        guard
            let stepPipe        = try? dev.makeComputePipelineState(function: stepFn),
            let colorizePipe    = try? dev.makeComputePipelineState(function: colorizeFn),
            let colorizeLitPipe = try? dev.makeComputePipelineState(function: colorizeLitFn)
        else { return nil }

        let rpd = MTLRenderPipelineDescriptor()
        rpd.vertexFunction                  = vertFn
        rpd.fragmentFunction                = fragFn
        rpd.colorAttachments[0].pixelFormat = .bgra8Unorm

        guard let renderPipe = try? dev.makeRenderPipelineState(descriptor: rpd)
        else { return nil }

        self.stepPipeline        = stepPipe
        self.colorizePipeline    = colorizePipe
        self.colorizeLitPipeline = colorizeLitPipe
        self.renderPipeline      = renderPipe

        // Simulation textures: rgba16Float, shared storage (CPU-writable for seeding).
        let simDesc = MTLTextureDescriptor.texture2DDescriptor(
            pixelFormat: .rgba16Float,
            width:       texSize,
            height:      texSize,
            mipmapped:   false
        )
        simDesc.usage       = [.shaderRead, .shaderWrite]
        simDesc.storageMode = .shared

        guard
            let ping = dev.makeTexture(descriptor: simDesc),
            let pong = dev.makeTexture(descriptor: simDesc)
        else { return nil }

        // Display texture: rgba8Unorm, GPU-private (never read back to CPU).
        let dispDesc = MTLTextureDescriptor.texture2DDescriptor(
            pixelFormat: .rgba8Unorm,
            width:       texSize,
            height:      texSize,
            mipmapped:   false
        )
        dispDesc.usage       = [.shaderRead, .shaderWrite]
        dispDesc.storageMode = .private

        guard let display = dev.makeTexture(descriptor: dispDesc) else { return nil }

        self.pingTex    = ping
        self.pongTex    = pong
        self.displayTex = display

        self.threadgroupSize  = MTLSize(width: 16, height: 16, depth: 1)
        self.threadgroupCount = MTLSize(
            width:  (texSize + 15) / 16,
            height: (texSize + 15) / 16,
            depth:  1
        )

        let s = config.preset
        let c = config.scheme
        self.simUniforms = SimUniforms(
            Du:     s.Du,
            Dv:     s.Dv,
            feed:   s.feed,
            kill:   s.kill,
            dt:     s.dt,
            width:  UInt32(texSize),
            height: UInt32(texSize)
        )
        self.colUniforms = ColourUniforms(
            low:      c.low,
            mid:      c.mid,
            high:     c.high,
            midPoint: c.midPoint,
            gamma:    c.gamma
        )

        // Initial lighting uniforms — direction will be updated each draw call.
        self.lightingUniforms = LightingUniforms(
            lightDir:    SIMD4(0, 0, 1, 0),
            lightColour: SIMD4(config.lighting.colour.x,
                               config.lighting.colour.y,
                               config.lighting.colour.z, 0),
            ambient:     config.lighting.ambient,
            diffuse:     config.lighting.diffuse,
            specular:    config.lighting.specular,
            shininess:   config.lighting.shininess,
            heightScale: config.lighting.heightScale
        )

        super.init()
        seed()
    }

    // MARK: - updateLighting
    // Called from MetalSimView.updateUIView — applies new lighting on the next
    // draw call without disturbing the running simulation state.

    func updateLighting(_ newLighting: PhysicsLighting) {
        lighting = newLighting
    }

    // MARK: - Seed
    // Plants the initial chemical state that the simulation evolves from.
    // A deterministic RNG (seeded with 0x50485942 — "PHYB" in ASCII) ensures
    // the pattern layout is identical every cold launch — no jarring randomness.

    private func seed() {
        var pixels = [Float16](repeating: .zero, count: texSize * texSize * 4)

        // Base state: U = 1.0 everywhere, V = 0.0
        for i in 0..<(texSize * texSize) {
            pixels[i * 4 + 0] = Float16(1.0)  // U
            pixels[i * 4 + 1] = Float16(0.0)  // V
            pixels[i * 4 + 2] = Float16(0.0)
            pixels[i * 4 + 3] = Float16(1.0)
        }

        // Soft circular V seed at (cx, cy) with given radius
        func plant(cx: Int, cy: Int, radius: Int) {
            for dy in -radius..<radius {
                for dx in -radius..<radius {
                    let x = cx + dx; let y = cy + dy
                    guard x >= 0, x < texSize, y >= 0, y < texSize else { continue }
                    let dist     = sqrt(Float(dx * dx + dy * dy))
                    let strength = max(0, 1.0 - dist / Float(radius))
                    let idx      = y * texSize + x
                    pixels[idx * 4 + 0] = Float16(1.0 - strength * 0.5)
                    pixels[idx * 4 + 1] = Float16(Float.random(in: 0.6...1.0) * strength)
                }
            }
        }

        // Centre seed — guarantees something visible immediately
        plant(cx: texSize / 2, cy: texSize / 2, radius: texSize / 10)

        // 24 scattered seeds — fills the field faster and looks richer from frame 1
        var rng = XorShift64(seed: 0x50485942)
        for _ in 0..<24 {
            let cx = Int(rng.next() % UInt64(texSize - 20)) + 10
            let cy = Int(rng.next() % UInt64(texSize - 20)) + 10
            let r  = Int(rng.next() % 10) + 4
            plant(cx: cx, cy: cy, radius: r)
        }

        pingTex.replace(
            region:      MTLRegionMake2D(0, 0, texSize, texSize),
            mipmapLevel: 0,
            withBytes:   &pixels,
            bytesPerRow: texSize * 4 * MemoryLayout<Float16>.stride
        )
    }

    // MARK: - MTKViewDelegate

    public func mtkView(_ view: MTKView, drawableSizeWillChange size: CGSize) { }

    public func draw(in view: MTKView) {
        guard
            let drawable       = view.currentDrawable,
            let renderPassDesc = view.currentRenderPassDescriptor,
            let cmdBuf         = commandQueue.makeCommandBuffer()
        else { return }

        // ── Update lighting uniforms ──────────────────────────────────────────
        // Light direction is recomputed every frame so animated orbits are smooth.
        // Non-animated lights use a fixed upper-right direction.
        let elapsed = Float(CACurrentMediaTime() - startTime)
        let angle: Float = lighting.animated
            ? elapsed * lighting.orbitSpeed * 2 * .pi / 60.0
            : 0.0
        let elev = lighting.elevation
        lightingUniforms = LightingUniforms(
            lightDir:    SIMD4(cos(angle) * cos(elev),
                               sin(angle) * cos(elev),
                               sin(elev), 0),
            lightColour: SIMD4(lighting.colour.x, lighting.colour.y, lighting.colour.z, 0),
            ambient:     lighting.ambient,
            diffuse:     lighting.diffuse,
            specular:    lighting.specular,
            shininess:   lighting.shininess,
            heightScale: lighting.heightScale
        )

        // ── Simulation steps — ping-pong compute ─────────────────────────────
        for _ in 0..<stepsPerFrame {
            guard let ce = cmdBuf.makeComputeCommandEncoder() else { continue }
            ce.setComputePipelineState(stepPipeline)
            ce.setTexture(pingTex, index: 0)
            ce.setTexture(pongTex, index: 1)
            ce.setBytes(&simUniforms, length: MemoryLayout<SimUniforms>.stride, index: 0)
            ce.dispatchThreadgroups(threadgroupCount, threadsPerThreadgroup: threadgroupSize)
            ce.endEncoding()
            swap(&pingTex, &pongTex)
        }

        // ── Colorize + light pass ─────────────────────────────────────────────
        // Use the Blinn-Phong kernel when lighting is active; fall back to the
        // flat colorize kernel when diffuse and specular are both zero — avoiding
        // the 5-tap normal reads when they would contribute nothing.
        if let ce = cmdBuf.makeComputeCommandEncoder() {
            if lighting.isActive {
                ce.setComputePipelineState(colorizeLitPipeline)
                ce.setTexture(pingTex,    index: 0)
                ce.setTexture(displayTex, index: 1)
                ce.setBytes(&colUniforms,     length: MemoryLayout<ColourUniforms>.stride,   index: 0)
                ce.setBytes(&lightingUniforms, length: MemoryLayout<LightingUniforms>.stride, index: 1)
            } else {
                ce.setComputePipelineState(colorizePipeline)
                ce.setTexture(pingTex,    index: 0)
                ce.setTexture(displayTex, index: 1)
                ce.setBytes(&colUniforms, length: MemoryLayout<ColourUniforms>.stride, index: 0)
            }
            ce.dispatchThreadgroups(threadgroupCount, threadsPerThreadgroup: threadgroupSize)
            ce.endEncoding()
        }

        // ── Blit display texture to drawable via full-screen quad ─────────────
        if let re = cmdBuf.makeRenderCommandEncoder(descriptor: renderPassDesc) {
            re.setRenderPipelineState(renderPipeline)
            re.setFragmentTexture(displayTex, index: 0)
            re.drawPrimitives(type: .triangleStrip, vertexStart: 0, vertexCount: 4)
            re.endEncoding()
        }

        cmdBuf.present(drawable)
        cmdBuf.commit()
    }
}

// MARK: - XorShift64
// Minimal deterministic PRNG for reproducible seed layouts.

private struct XorShift64 {
    private var state: UInt64
    init(seed: UInt64) { state = seed == 0 ? 1 : seed }
    mutating func next() -> UInt64 {
        state ^= state << 13
        state ^= state >> 7
        state ^= state << 17
        return state
    }
}
